version: 2.1

workflows:
  build:
    jobs:
      - build-and-test


jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Setup jupyter-repo2docker
          command: pip install jupyter-repo2docker

      - run:
          name: Build image
          command: |
            jupyter-repo2docker \
              --user-id 1000 --user-name jovyan \
              .
